---
abstract: 'Text::Haml template engine wrapper for Dancer2'
author:
  - 'Viacheslav Koval, <athlete AT cpan DOT org>'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.9.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Template-Haml
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Dancer2::Template::Haml:
    file: lib/Dancer2/Template/Haml.pm
    version: 0.04
requires:
  Carp: 0
  Dancer2::Core::Role::Template: 0
  Dancer2::Core::Types: 0
  Dancer2::FileUtils: 0
  Moo: 0
  Text::Haml: 0
  perl: 5.008005
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/TheAthlete/Dancer2-Template-Haml/issues
  homepage: https://github.com/TheAthlete/Dancer2-Template-Haml
  repository: https://github.com/TheAthlete/Dancer2-Template-Haml.git
version: 0.04
x_contributors:
  - 'TheAthlete <theathlet@yandex.ru>'
